language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
addons:
  apt:
    packages:
    - openssl
script:
  - PYTHONWARNINGS="ignore:Unverified HTTPS request" python -u ./livetest.py 1>&2
